[workspace]
members = ["android", "client", "packets", "scripts", "server", "structures"]
resolver = "2"

[workspace.package]
version = "0.74.0"

[profile.dev]
opt-level = 1

[profile.dev-fast]
inherits = "dev"
opt-level = 0

[profile.release]
lto = true
